### ISSUE TITLE
issue with column name 'class' when using with facet_wrap()

### ISSUE THREAD

**Issue by psychometrician** [has2k1/plotnine#78] opened 2017-11-08 03:39 UTC
ggplot(mpg, aes('displ','hwy')) + geom_point() + facet_wrap('~class') 

 File "<string>", line 1
    class
        ^
SyntaxError: unexpected EOF while parsing

when changed into other name like 'classcat' it worked.

**Comment by has2k1** [comment] 2017-11-08 05:20
Duplicate of #28.

**Closed by has2k1** 2017-11-08 05:20 UTC
Labels: duplicate
