### ISSUE TITLE
legend position not reproducible 

### ISSUE THREAD

**Issue by yunfeiguo** [has2k1/plotnine#299] opened 2019-08-14 02:15 UTC
Hi I have a weird issue where the legends for `shape` and `color` are not fixed (in `geom_point`), sometimes `shape` is on top of `color` and sometimes `color` is on top of `shape`. The inputs are exactly the same. The code is the same as well.

I have not found a way to reproduce the issue with a small example.

I wonder what could possibly lead to this situation? And how to fix the position of `shape` and `color` legends. Thanks.

code for plotting
```
fig = ggplot(df)
fig = fig + geom_point(aes(
            x='type', y='rate', color='sample', shape='dup'),
                               size=2,
                               alpha=0.4)
fig = fig + ylab('rate') + facet_grid('aln_setting~.')
fig.save("plot.png")
```

**Comment by has2k1** [comment] 2019-08-14 13:36
Duplicate of #229 and was fixed in https://github.com/has2k1/plotnine/commit/739472545098afbda438c6f39636db1c69215d4f. It will ship in the next release.

**Closed** 2019-08-14 13:36 UTC
Labels: duplicate, invalid

**Comment by yunfeiguo** [comment] 2019-08-14 13:57
Great, thanks!
