### ISSUE TITLE
is there gridExtra/cowplot type package in Python to use with Plotnine to align subplots (i.e. marginal distributions)

### ISSUE THREAD

**Issue by algotr8der** [has2k1/plotnine#331] opened 2019-11-15 15:48 UTC
https://stackoverflow.com/questions/58775754/is-there-gridextra-cowplot-type-package-in-python-to-use-with-plotnine-to-align

This is related to the following posts on aligning subplots in ggplot2 in R:

Scatterplot with marginal histograms in ggplot2
https://stackoverflow.com/questions/8545035/scatterplot-with-marginal-histograms-in-ggplot2

How to plot Scatters with marginal density plots use Python?
https://stackoverflow.com/questions/52789143/how-to-plot-scatters-with-marginal-density-plots-use-python

Perfectly align several plots
https://stackoverflow.com/questions/38637261/perfectly-align-several-plots/38640937#38640937

There are many more links on StackOverflow on this topic.

Anyhow, I haven't been able to find any documentation on how to do this with Plotnine (ggplot2 implementation) in Python.

Can this be done at all in Python? If not has there not been any demand for a solution to this problem?

Thank you for your guidance.

UPDATE:

I found this link MEP for a matplotlib geometry manager #1109:

https://github.com/matplotlib/matplotlib/issues/1109

which seems to indicate that the functionality is now present in matplotlib to do this. The question is has plotnine been extended to do this?

**Comment by xguse** [comment] 2019-11-15 16:01
I just posted an answer to your stackoverflow question. But the basic answer is plotnine seems to aim to specifically cover what gglot2 itself can do and not what ggplot2 + X-other-supplemental-R-pkg can do.

However seaborn does this kind of stuff VERY easily. See the  SO post for the link and example code.

**Comment by has2k1** [comment] 2019-11-15 16:43
> which seems to indicate that the functionality is now present in matplotlib to do this. The question is has plotnine been extended to do this? 

Yes the geometry manager was implemented, but the result was not what I had hoped for. It is restricted in how you can use it in ways that make it hard for plotnine.

plotnine needs a plot manager that makes it easy to stack and align all kinds of objects/artists, not just the plot area(s). The more stuff you can have outside the plot area the harder it becomes.

One of the objectives is to make plotnine easily extendable so that other packages can depend on it.

I am closing this issue as it is a duplicate of #46.

**Closed by has2k1** 2019-11-15 16:43 UTC
