### ISSUE TITLE
Minus sign not shown in xkcd theme

### ISSUE THREAD

**Issue by bersbersbers** [has2k1/plotnine#451] opened 2020-10-26 15:01 UTC
```
import pandas as pd
from plotnine import aes, ggplot, theme_xkcd

df = pd.DataFrame([[-10, 10], [10, -10]], columns=["x", "y"])
print(ggplot(df) + aes(x="x", y="y") + theme_xkcd())
```

This yields this:
![image](https://user-images.githubusercontent.com/12128514/97189033-77633d80-17a4-11eb-92a4-47038e28538f.png)

Manually adding
```
matplotlib.rcParams["axes.unicode_minus"] = False
```
solves the problem, but I had expected this section to take care of this:

https://github.com/has2k1/plotnine/blob/52e33218b86165d90f5313d57c22465223219e98/plotnine/themes/theme_xkcd.py#L61-L68

**Comment by has2k1** [comment] 2020-10-26 21:09
I cannot reproduce it!

```python
import pandas as pd
from plotnine import aes, ggplot, theme_xkcd
df = pd.DataFrame([[-10, 10], [10, -10]], columns=["x", "y"])
ggplot(df) + aes(x="x", y="y") + theme_xkcd()
```

![xkcd-minus](https://user-images.githubusercontent.com/780341/97228943-ab605200-17e8-11eb-920d-cca4b20ff902.png)

**Comment by bersbersbers** [comment] 2020-10-27 08:07
Well, you are using a different font, aren't you? I should have stated that I have installed* `xkcd.ttf` from http://simonsoftware.se/other/xkcd.ttf, which does not have glyphs for the unicode minus used for the negative axis labels. But I guess this is exactly what `'axes.unicode_minus': False` is for, so I'd expect that to work, too.

(*)
```
wget http://simonsoftware.se/other/xkcd.ttf -O ~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/matplotlib/mpl-data/fonts/ttf/xkcd.ttf
rm ~/.cache/matplotlib/fontlist-v330.json
```

**Comment by has2k1** [comment] 2020-11-30 22:23
Fixed in https://github.com/has2k1/plotnine/commit/0bdec2a2f2847f26ceaf38f0b65d7ff475ab7f61.

**Closed by has2k1** 2020-11-30 22:23 UTC
Labels: bug
