### ISSUE TITLE
Faceting does not work with quantile-quantile plots 

### ISSUE THREAD

**Issue by swenlaur** [has2k1/plotnine#382] opened 2020-04-09 11:10 UTC
Faceting does not seem to work with `geom_qq`. The minimal example is following. 
```
from scipy.stats import norm
df1 = DataFrame({'x': norm.rvs(size=30), 'facet': list(range(3)) *  10})
ggplot(df1) + geom_qq(aes(sample='x')) + facet_wrap('facet')
```

I would expect to see a three facets with 10 point in each but instead only one is filled and I get an error message.

**Comment by has2k1** [comment] 2020-04-09 20:57
This issue was fixed and will ship in the next release.

Duplicate of #379.

**Closed by has2k1** 2020-04-09 20:57 UTC
Labels: duplicate
