### ISSUE TITLE
`Bunch` deprecate warning with matplotlib 3.0

### ISSUE THREAD

**Issue by kongscn** [has2k1/plotnine#206] opened 2018-10-10 02:08 UTC
```
MatplotlibDeprecationWarning: The Bunch class was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use types.SimpleNamespace instead.
```

**Comment by has2k1** [comment] 2018-10-10 08:03
Duplicate of #205.

**Closed by has2k1** 2018-10-10 08:03 UTC
Labels: duplicate
