### ISSUE TITLE
Can't use `facet_wrap` with `geom_map`?

### ISSUE THREAD

**Issue by AlFontal** [has2k1/plotnine#387] opened 2020-04-21 08:53 UTC
I am aware `geom_map` was implemented with limited functionality since it uses `geopandas`, and it possibly makes it quite hard to emulate the whole functionality of `ggplot`. 

Nevertheless, I am unable to use `geom_map` together with `facet_wrap` and keep getting a quite cryptic `KeyError: 0` message whenever I attempt to run it. 

Am I supposed to be able to use this or is this just not implemented? If it should, I can work out a small minimal example to showcase the issue.

**Comment by has2k1** [comment] 2020-04-21 12:27
This is a duplicate of #359, which has been fixed but has not yet been released. Use the development branch if you need can.

```
$ pip install git+https://github.com/has2k1/plotnine.git
```

**Closed by has2k1** 2020-04-21 12:27 UTC
Labels: duplicate, invalid

**Comment by has2k1** [comment] 2020-04-21 16:36
> I'll just use the dev branch then! Thanks!

I meant the *master* branch, which that is what is installed by that command.
