### ISSUE TITLE
New MatplotlibDepreciationWarnings

### ISSUE THREAD

**Issue by bkohrn** [has2k1/plotnine#279] opened 2019-06-03 20:44 UTC
I just installed plotnine (v0.5.1) with the idea of testing it out.  On installation, it also updated my matplotlib to 3.1.0.  When I ran the following code:

```
from plotnine import *
from plotnine.data import mtcars
(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear'))
```

I got the following warnings:

> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/scales/scale.py:93: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   if cbook.iterable(self.breaks) and cbook.iterable(self.labels):
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/scales/scale.py:93: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   if cbook.iterable(self.breaks) and cbook.iterable(self.labels):
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/scales/scale.py:93: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   if cbook.iterable(self.breaks) and cbook.iterable(self.labels):
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:52: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
>   return getattr(obj, method)(*args, **kwds)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:52: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
>   return getattr(obj, method)(*args, **kwds)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:52: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
>   return getattr(obj, method)(*args, **kwds)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plotnine/utils.py:553: MatplotlibDeprecationWarning: 
> The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
>   return cbook.iterable(var) and not is_string(var)

I'm working on MacOS X Sierra, using Python 3.6.4 and JupyterLab v 0.35.4

Other than the long list of warnings being a bit annoying, the code still works, so this is not as much an issue as a notice that there seems to be an issue possibly coming up in the near future.

**Comment by has2k1** [comment] 2019-06-04 11:34
Duplicate of #276, which has been addressed.

**Closed by has2k1** 2019-06-04 11:34 UTC
