### ISSUE TITLE
Switch on facets

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#246] opened 2019-01-14 13:36 UTC
ggplot now offers a parameter switch on facets that allows putting the strip on the left/bottom instead of right/top:

"switch
By default, the labels are displayed on the top and right of the plot. If "x", the top labels will be displayed to the bottom. If "y", the right-hand side labels will be displayed to the left. Can also be set to "both"."

This allows plots like the following:
![image](https://user-images.githubusercontent.com/1257580/51115725-616fcd00-1809-11e9-8294-c868b86fb15f.png)

Would be nice to have in plotnine as well.

**Comment by has2k1** [comment] 2019-01-19 14:04
This is just another feature that we cannot do well without a good plot manager. So it is a duplicate of #46.

**Closed by has2k1** 2019-01-19 14:04 UTC

**Comment by TyberiusPrime** [comment] 2019-01-19 20:10
Maybe we can expose both the box y pos (already done) and the text y pos (not exposed currently) for the facet labels? It wouldn't be ideal, but would allow the user to fudge it for a fixed plot size.

**Comment by has2k1** [comment] 2019-01-21 07:59
I am reluctant to touch the code that handles facet labels other than in the case switching to a good layout manager.

However, you can get some extra mileage out of the `strip_margin` themeable. See `theme_xkcd`.
