### ISSUE TITLE
Implement caption and subtitle parameters for labs

### ISSUE THREAD

**Issue by h-joshi** [has2k1/plotnine#313] opened 2019-09-06 00:31 UTC
labs 'caption' parameter is particularly handy when annotating observation counts
![image](https://user-images.githubusercontent.com/1222657/64392718-523bd900-d091-11e9-8496-fab614f4967b.png)

**Comment by has2k1** [comment] 2019-09-06 13:55
Duplicate of #177.

**Closed by has2k1** 2019-09-06 13:55 UTC
Labels: duplicate, feature
